[package]
name = "financial_verify"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.5", default-features = false, features = ['std'] }
zeroproof-core = {path = "../../core"}
serde_json = "1.0"
